;;;; Grovelled against ICU headers at overlay build (or local-dev with headers).
;;;; Consumers with cl-repository overlays load grovel-cache/ — no CC required.
;;;;
;;;; Include search: set CPATH or CL_STACK_ICU_INCLUDE on builders.
;;;; Local-dev also picks up Homebrew via cc-flags below.
;;;;
;;;; Note: this file is DSL for cffi-grovel — only grovel forms (or #. that
;;;; expand to them). Plain LET/WHEN are unknown syntax.
(in-package #:cl-stack-icu)

#.(let* ((inc (uiop:getenv "CL_STACK_ICU_INCLUDE"))
         (extra (when (and inc (plusp (length inc)))
                  (list (format nil "-I~A/" (string-right-trim "/" inc)))))
         (hb (uiop:getenv "HOMEBREW_PREFIX"))
         (hb-flags (when (and hb (plusp (length hb)))
                     (list (format nil "-I~A/opt/icu4c/include/" hb)
                           (format nil "-I~A/opt/icu4c@78/include/" hb)
                           (format nil "-I~A/include/" hb)))))
    `(cc-flags ,@extra
               ,@(or hb-flags '())
               "-I/usr/local/include/"
               "-I/opt/homebrew/include/"
               "-I/opt/homebrew/opt/icu4c/include/"
               "-I/usr/include/"
               "-Ic:/icu/include/"
               "-Ic:/include/"))

(include "unicode/utypes.h")
(include "unicode/uversion.h")
(include "unicode/ustring.h")
(include "unicode/uchar.h")
(include "unicode/unorm2.h")
(include "unicode/ubrk.h")
(include "unicode/uidna.h")
(include "unicode/uloc.h")
(include "unicode/ures.h")
(include "unicode/ucol.h")
(include "unicode/unum.h")
(include "unicode/udat.h")
(include "unicode/upluralrules.h")
(include "unicode/ulistformatter.h")
(include "unicode/unumberformatter.h")
(include "unicode/uformattedvalue.h")
(include "unicode/uformattednumber.h")
(include "unicode/uset.h")
(include "unicode/ureldatefmt.h")
(include "unicode/udisplaycontext.h")

(ctype u-char "UChar")
(ctype u-char32 "UChar32")
(ctype u-bool "UBool")

(constant (u-icu-version-major-num "U_ICU_VERSION_MAJOR_NUM"))
(constant (u-icu-version-minor-num "U_ICU_VERSION_MINOR_NUM"))
(constant (u-icu-version-patchlevel-num "U_ICU_VERSION_PATCHLEVEL_NUM"))
(constant (u-max-version-length "U_MAX_VERSION_LENGTH"))
(constant (u-max-version-string-length "U_MAX_VERSION_STRING_LENGTH"))

(constant (u-fold-case-default "U_FOLD_CASE_DEFAULT"))
(constant (u-fold-case-exclude-special-i "U_FOLD_CASE_EXCLUDE_SPECIAL_I"))

;;; UIDNA_* live in an anonymous enum (not #define) — use cenum, not constant.
(cenum (uidna-option)
  ((:default "UIDNA_DEFAULT"))
  ((:use-std3-rules "UIDNA_USE_STD3_RULES"))
  ((:check-bidi "UIDNA_CHECK_BIDI"))
  ((:check-contextj "UIDNA_CHECK_CONTEXTJ"))
  ((:check-contexto "UIDNA_CHECK_CONTEXTO"))
  ((:nontransitional-to-ascii "UIDNA_NONTRANSITIONAL_TO_ASCII"))
  ((:nontransitional-to-unicode "UIDNA_NONTRANSITIONAL_TO_UNICODE")))

(cenum (u-error-code)
  ((:using-fallback-warning "U_USING_FALLBACK_WARNING"))
  ((:error-warning-start "U_ERROR_WARNING_START"))
  ((:using-default-warning "U_USING_DEFAULT_WARNING"))
  ((:string-not-terminated-warning "U_STRING_NOT_TERMINATED_WARNING"))
  ((:zero-error "U_ZERO_ERROR"))
  ((:illegal-argument-error "U_ILLEGAL_ARGUMENT_ERROR"))
  ((:missing-resource-error "U_MISSING_RESOURCE_ERROR"))
  ((:invalid-format-error "U_INVALID_FORMAT_ERROR"))
  ((:memory-allocation-error "U_MEMORY_ALLOCATION_ERROR"))
  ((:index-outofbounds-error "U_INDEX_OUTOFBOUNDS_ERROR"))
  ((:parse-error "U_PARSE_ERROR"))
  ((:invalid-char-found "U_INVALID_CHAR_FOUND"))
  ((:truncated-char-found "U_TRUNCATED_CHAR_FOUND"))
  ((:illegal-char-found "U_ILLEGAL_CHAR_FOUND"))
  ((:buffer-overflow-error "U_BUFFER_OVERFLOW_ERROR"))
  ((:unsupported-error "U_UNSUPPORTED_ERROR"))
  ((:resource-type-mismatch "U_RESOURCE_TYPE_MISMATCH"))
  ((:illegal-escape-sequence "U_ILLEGAL_ESCAPE_SEQUENCE"))
  ((:unsupported-escape-sequence "U_UNSUPPORTED_ESCAPE_SEQUENCE"))
  ((:no-space-available "U_NO_SPACE_AVAILABLE"))
  ((:invalid-state-error "U_INVALID_STATE_ERROR"))
  ((:standard-error-limit "U_STANDARD_ERROR_LIMIT")))

(cenum (u-char-category)
  ((:unassigned "U_UNASSIGNED"))
  ((:uppercase-letter "U_UPPERCASE_LETTER"))
  ((:lowercase-letter "U_LOWERCASE_LETTER"))
  ((:titlecase-letter "U_TITLECASE_LETTER"))
  ((:modifier-letter "U_MODIFIER_LETTER"))
  ((:other-letter "U_OTHER_LETTER"))
  ((:non-spacing-mark "U_NON_SPACING_MARK"))
  ((:enclosing-mark "U_ENCLOSING_MARK"))
  ((:combining-spacing-mark "U_COMBINING_SPACING_MARK"))
  ((:decimal-digit-number "U_DECIMAL_DIGIT_NUMBER"))
  ((:letter-number "U_LETTER_NUMBER"))
  ((:other-number "U_OTHER_NUMBER"))
  ((:space-separator "U_SPACE_SEPARATOR"))
  ((:line-separator "U_LINE_SEPARATOR"))
  ((:paragraph-separator "U_PARAGRAPH_SEPARATOR"))
  ((:control-char "U_CONTROL_CHAR"))
  ((:format-char "U_FORMAT_CHAR"))
  ((:private-use-char "U_PRIVATE_USE_CHAR"))
  ((:surrogate "U_SURROGATE"))
  ((:dash-punctuation "U_DASH_PUNCTUATION"))
  ((:start-punctuation "U_START_PUNCTUATION"))
  ((:end-punctuation "U_END_PUNCTUATION"))
  ((:connector-punctuation "U_CONNECTOR_PUNCTUATION"))
  ((:other-punctuation "U_OTHER_PUNCTUATION"))
  ((:math-symbol "U_MATH_SYMBOL"))
  ((:currency-symbol "U_CURRENCY_SYMBOL"))
  ((:modifier-symbol "U_MODIFIER_SYMBOL"))
  ((:other-symbol "U_OTHER_SYMBOL"))
  ((:initial-punctuation "U_INITIAL_PUNCTUATION"))
  ((:final-punctuation "U_FINAL_PUNCTUATION")))

;;; Binary / int property subset used by unicode-protocol backends.
(cenum (u-property)
  ((:alphabetic "UCHAR_ALPHABETIC"))
  ((:ascii-hex-digit "UCHAR_ASCII_HEX_DIGIT"))
  ((:bidi-control "UCHAR_BIDI_CONTROL"))
  ((:bidi-mirrored "UCHAR_BIDI_MIRRORED"))
  ((:dash "UCHAR_DASH"))
  ((:default-ignorable-code-point "UCHAR_DEFAULT_IGNORABLE_CODE_POINT"))
  ((:deprecated "UCHAR_DEPRECATED"))
  ((:diacritic "UCHAR_DIACRITIC"))
  ((:extender "UCHAR_EXTENDER"))
  ((:full-composition-exclusion "UCHAR_FULL_COMPOSITION_EXCLUSION"))
  ((:grapheme-base "UCHAR_GRAPHEME_BASE"))
  ((:grapheme-extend "UCHAR_GRAPHEME_EXTEND"))
  ((:hex-digit "UCHAR_HEX_DIGIT"))
  ((:hyphen "UCHAR_HYPHEN"))
  ((:id-continue "UCHAR_ID_CONTINUE"))
  ((:id-start "UCHAR_ID_START"))
  ((:ideographic "UCHAR_IDEOGRAPHIC"))
  ((:ids-binary-operator "UCHAR_IDS_BINARY_OPERATOR"))
  ((:ids-trinary-operator "UCHAR_IDS_TRINARY_OPERATOR"))
  ((:join-control "UCHAR_JOIN_CONTROL"))
  ((:logical-order-exception "UCHAR_LOGICAL_ORDER_EXCEPTION"))
  ((:lowercase "UCHAR_LOWERCASE"))
  ((:math "UCHAR_MATH"))
  ((:noncharacter-code-point "UCHAR_NONCHARACTER_CODE_POINT"))
  ((:quotation-mark "UCHAR_QUOTATION_MARK"))
  ((:radical "UCHAR_RADICAL"))
  ((:soft-dotted "UCHAR_SOFT_DOTTED"))
  ((:terminal-punctuation "UCHAR_TERMINAL_PUNCTUATION"))
  ((:unified-ideograph "UCHAR_UNIFIED_IDEOGRAPH"))
  ((:uppercase "UCHAR_UPPERCASE"))
  ((:white-space "UCHAR_WHITE_SPACE"))
  ((:xid-continue "UCHAR_XID_CONTINUE"))
  ((:xid-start "UCHAR_XID_START"))
  ((:case-sensitive "UCHAR_CASE_SENSITIVE"))
  ((:s-term "UCHAR_S_TERM"))
  ((:variation-selector "UCHAR_VARIATION_SELECTOR"))
  ((:nfd-inert "UCHAR_NFD_INERT"))
  ((:nfkd-inert "UCHAR_NFKD_INERT"))
  ((:nfc-inert "UCHAR_NFC_INERT"))
  ((:nfkc-inert "UCHAR_NFKC_INERT"))
  ((:segment-starter "UCHAR_SEGMENT_STARTER"))
  ((:pattern-syntax "UCHAR_PATTERN_SYNTAX"))
  ((:pattern-white-space "UCHAR_PATTERN_WHITE_SPACE"))
  ((:posix-alnum "UCHAR_POSIX_ALNUM"))
  ((:posix-blank "UCHAR_POSIX_BLANK"))
  ((:posix-graph "UCHAR_POSIX_GRAPH"))
  ((:posix-print "UCHAR_POSIX_PRINT"))
  ((:posix-xdigit "UCHAR_POSIX_XDIGIT"))
  ((:cased "UCHAR_CASED"))
  ((:case-ignorable "UCHAR_CASE_IGNORABLE"))
  ((:changes-when-lowercased "UCHAR_CHANGES_WHEN_LOWERCASED"))
  ((:changes-when-uppercased "UCHAR_CHANGES_WHEN_UPPERCASED"))
  ((:changes-when-titlecased "UCHAR_CHANGES_WHEN_TITLECASED"))
  ((:changes-when-casefolded "UCHAR_CHANGES_WHEN_CASEFOLDED"))
  ((:changes-when-casemapped "UCHAR_CHANGES_WHEN_CASEMAPPED"))
  ((:changes-when-nfkc-casefolded "UCHAR_CHANGES_WHEN_NFKC_CASEFOLDED"))
  ((:emoji "UCHAR_EMOJI"))
  ((:emoji-presentation "UCHAR_EMOJI_PRESENTATION"))
  ((:emoji-modifier "UCHAR_EMOJI_MODIFIER"))
  ((:emoji-modifier-base "UCHAR_EMOJI_MODIFIER_BASE"))
  ((:emoji-component "UCHAR_EMOJI_COMPONENT"))
  ((:regional-indicator "UCHAR_REGIONAL_INDICATOR"))
  ((:prepended-concatenation-mark "UCHAR_PREPENDED_CONCATENATION_MARK"))
  ((:extended-pictographic "UCHAR_EXTENDED_PICTOGRAPHIC"))
  ((:bidi-class "UCHAR_BIDI_CLASS"))
  ((:block "UCHAR_BLOCK"))
  ((:canonical-combining-class "UCHAR_CANONICAL_COMBINING_CLASS"))
  ((:decomposition-type "UCHAR_DECOMPOSITION_TYPE"))
  ((:east-asian-width "UCHAR_EAST_ASIAN_WIDTH"))
  ((:general-category "UCHAR_GENERAL_CATEGORY"))
  ((:joining-group "UCHAR_JOINING_GROUP"))
  ((:joining-type "UCHAR_JOINING_TYPE"))
  ((:line-break "UCHAR_LINE_BREAK"))
  ((:numeric-type "UCHAR_NUMERIC_TYPE"))
  ((:script "UCHAR_SCRIPT"))
  ((:hangul-syllable-type "UCHAR_HANGUL_SYLLABLE_TYPE"))
  ((:nfd-quick-check "UCHAR_NFD_QUICK_CHECK"))
  ((:nfkd-quick-check "UCHAR_NFKD_QUICK_CHECK"))
  ((:nfc-quick-check "UCHAR_NFC_QUICK_CHECK"))
  ((:nfkc-quick-check "UCHAR_NFKC_QUICK_CHECK"))
  ((:lead-canonical-combining-class "UCHAR_LEAD_CANONICAL_COMBINING_CLASS"))
  ((:trail-canonical-combining-class "UCHAR_TRAIL_CANONICAL_COMBINING_CLASS"))
  ((:grapheme-cluster-break "UCHAR_GRAPHEME_CLUSTER_BREAK"))
  ((:sentence-break "UCHAR_SENTENCE_BREAK"))
  ((:word-break "UCHAR_WORD_BREAK"))
  ((:indic-positional-category "UCHAR_INDIC_POSITIONAL_CATEGORY"))
  ((:indic-syllabic-category "UCHAR_INDIC_SYLLABIC_CATEGORY"))
  ((:vertical-orientation "UCHAR_VERTICAL_ORIENTATION")))

(cenum (u-break-iterator-type)
  ((:character "UBRK_CHARACTER"))
  ((:word "UBRK_WORD"))
  ((:line "UBRK_LINE"))
  ((:sentence "UBRK_SENTENCE")))

(cenum (u-col-attribute-value)
  ((:default "UCOL_DEFAULT"))
  ((:primary "UCOL_PRIMARY"))
  ((:secondary "UCOL_SECONDARY"))
  ((:tertiary "UCOL_TERTIARY"))
  ((:default-strength "UCOL_DEFAULT_STRENGTH"))
  ((:quaternary "UCOL_QUATERNARY"))
  ((:identical "UCOL_IDENTICAL"))
  ((:off "UCOL_OFF"))
  ((:on "UCOL_ON")))

(cenum (u-collation-result)
  ((:equal "UCOL_EQUAL"))
  ((:greater "UCOL_GREATER"))
  ((:less "UCOL_LESS")))

(cenum (u-number-format-style)
  ((:pattern-decimal "UNUM_PATTERN_DECIMAL"))
  ((:decimal "UNUM_DECIMAL"))
  ((:currency "UNUM_CURRENCY"))
  ((:percent "UNUM_PERCENT"))
  ((:scientific "UNUM_SCIENTIFIC"))
  ((:currency-iso "UNUM_CURRENCY_ISO"))
  ((:currency-plural "UNUM_CURRENCY_PLURAL"))
  ((:currency-accounting "UNUM_CURRENCY_ACCOUNTING"))
  ((:cash-currency "UNUM_CASH_CURRENCY"))
  ((:decimal-compact-short "UNUM_DECIMAL_COMPACT_SHORT"))
  ((:decimal-compact-long "UNUM_DECIMAL_COMPACT_LONG"))
  ((:currency-standard "UNUM_CURRENCY_STANDARD"))
  ((:default "UNUM_DEFAULT")))

(cenum (u-date-format-style)
  ((:full "UDAT_FULL"))
  ((:long "UDAT_LONG"))
  ((:medium "UDAT_MEDIUM"))
  ((:short "UDAT_SHORT"))
  ((:default "UDAT_DEFAULT"))
  ((:none "UDAT_NONE"))
  ((:pattern "UDAT_PATTERN")))

(cenum (u-plural-type)
  ((:cardinal "UPLURAL_TYPE_CARDINAL"))
  ((:ordinal "UPLURAL_TYPE_ORDINAL")))

(cenum (u-list-formatter-type)
  ((:and "ULISTFMT_TYPE_AND"))
  ((:or "ULISTFMT_TYPE_OR"))
  ((:units "ULISTFMT_TYPE_UNITS")))

(cenum (u-list-formatter-width)
  ((:wide "ULISTFMT_WIDTH_WIDE"))
  ((:short "ULISTFMT_WIDTH_SHORT"))
  ((:narrow "ULISTFMT_WIDTH_NARROW")))

(cenum (u-res-type)
  ((:none "URES_NONE"))
  ((:string "URES_STRING"))
  ((:binary "URES_BINARY"))
  ((:table "URES_TABLE"))
  ((:alias "URES_ALIAS"))
  ((:int "URES_INT"))
  ((:array "URES_ARRAY"))
  ((:int-vector "URES_INT_VECTOR")))

(cenum (u-char-name-choice)
  ((:unicode "U_UNICODE_CHAR_NAME"))
  ((:extended "U_EXTENDED_CHAR_NAME"))
  ((:alias "U_CHAR_NAME_ALIAS")))

(cenum (u-property-name-choice)
  ((:short "U_SHORT_PROPERTY_NAME"))
  ((:long "U_LONG_PROPERTY_NAME")))

(cenum (u-set-span-condition)
  ((:not-contained "USET_SPAN_NOT_CONTAINED"))
  ((:contained "USET_SPAN_CONTAINED"))
  ((:simple "USET_SPAN_SIMPLE")))

(cenum (u-relative-date-time-unit)
  ((:year "UDAT_REL_UNIT_YEAR"))
  ((:quarter "UDAT_REL_UNIT_QUARTER"))
  ((:month "UDAT_REL_UNIT_MONTH"))
  ((:week "UDAT_REL_UNIT_WEEK"))
  ((:day "UDAT_REL_UNIT_DAY"))
  ((:hour "UDAT_REL_UNIT_HOUR"))
  ((:minute "UDAT_REL_UNIT_MINUTE"))
  ((:second "UDAT_REL_UNIT_SECOND"))
  ((:sunday "UDAT_REL_UNIT_SUNDAY"))
  ((:monday "UDAT_REL_UNIT_MONDAY"))
  ((:tuesday "UDAT_REL_UNIT_TUESDAY"))
  ((:wednesday "UDAT_REL_UNIT_WEDNESDAY"))
  ((:thursday "UDAT_REL_UNIT_THURSDAY"))
  ((:friday "UDAT_REL_UNIT_FRIDAY"))
  ((:saturday "UDAT_REL_UNIT_SATURDAY")))

(cenum (u-date-relative-date-time-formatter-style)
  ((:long "UDAT_STYLE_LONG"))
  ((:short "UDAT_STYLE_SHORT"))
  ((:narrow "UDAT_STYLE_NARROW")))

(constant (u-no-numeric-value "U_NO_NUMERIC_VALUE") :type double-float)
;;; UDISPCTX_* are enum values (not #defines) — hardcode in ffi-extra.lisp.
